[package]
name = "udp2mic"
version = "1.0.9"
edition = "2021"
description = "UDP2Mic - 局域网麦克风Windows接收端"
build = "build.rs"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "unwind"
strip = "symbols"

[build-dependencies]
winres = "0.1"
image = "0.24"

[dependencies]
udp2mic-protocol = { path = "../protocol" }
iced = { version = "0.14", default-features = false, features = ["tokio", "tiny-skia", "image"] }
tokio = { version = "1.40", features = ["net", "sync", "rt", "macros", "time"] }
cpal = "0.15"
windows = { version = "0.58", features = [
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_Foundation",
] }
winreg = "0.52"
audiopus = "0.3.0-rc.0"
tray-icon = "0.24.0"
image = "0.24"